- hosts: localhost
  vars:
    - java_jdk_version: 17
  
  tasks:
    - name: install basic packages 
      apt: >
        name={{item}} 
        state=present
      with_items:
        - curl
        - net-tools
        - htop

    - name: install Java JDK 
      apt: > 
        name=openjdk-{{java_jdk_version}}-jdk 
        state=present

    - name: install VSCode IDE
      snap: >
        name=code 
        state=present

    # - name: install Oh My Bash
    - 
    # - name: install Chrome

    
